### ISSUE TITLE
No CPU info for Ryzen

### ISSUE THREAD

**Issue by kbknapp** [cjbassi/gotop#102]
Required information:

- gotop version (`gotop -v`): 2.0.0
- The output of `uname -a`: Linux thebeast 4.20.5-042005-generic #201901260434 SMP Sat Jan 26 09:36:17 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Terminal shell (e.g. zsh or bash): zsh
- Terminal emulator (e.g. iTerm or gnome terminal): Tilix
- Any relevenat hardware info: CPU is an AMD Ryzen Threadripper 2950x
- tmux version if using tmux: N/A

Also please copy or attach the following file if it exists and contains logs:

- Linux: `~/.local/state/gotop/errors.log` Empty

---

No CPU core info, just shows "AVRG". I thought this may be a terminal size thing, so I full screened a vertical monitor, but same.

I understand showing 16 cores or 32 threads is a bit much, so maybe showing like top 8 by load? Just some thoughts.

**Comment by cjbassi** [comment]
So gotop defaults to only showing average if there are more than 8 cores. But you can use the `-p` and `-a` flags to customize that. Let me know if those don't work or if you have other suggestions.

**Comment by kbknapp** [comment]
Ah cool, can't believe I missed that! Thanks!
