### ISSUE TITLE
Process list scroll indicator

### ISSUE THREAD

**Issue by A-lxe** [cjbassi/gotop#127]
It would be nice if the process list had some kind of scroll indicator that shows where the currently selected process is in the list, as well as the overall size of the list. Currently I scroll down and lose track of where I am pretty quickly.

Possible indicators:
* a `[selected]/[total]` text placed somewhere in the widget, ie ┏ Processes ━━━━ 10 / 453 ┓
* a scroll bar to the right of the list
* line numbers, maybe with a switch like -N in less

I would be happy to try implementing this if y'all think it's a good idea!

**Comment by cjbassi** [comment]
Added in 56662fda14240e21f6f7bc175b988a25d92f0570
