### ISSUE TITLE
FreeBSD: process list empty

### ISSUE THREAD

**Issue by herrbischoff** [cjbassi/gotop#134]
Required information:

- gotop version (`gotop -V`): 3.0.0
- The output of `uname -a`: FreeBSD [REDACTED] 12.0-RELEASE-p3 FreeBSD 12.0-RELEASE-p3 GENERIC  amd64
- Terminal emulator (e.g. iTerm or gnome terminal): kitty
- Any relevenat hardware info: n/a
- tmux version if using tmux: n/a

Also please copy or attach `~/.local/state/gotop/errors.log` if it exists and contains logs: n/a

## Problem

The process list (and temperatures list) does not contain the information it should. See screenshot:

![Screenshot 2019-04-07 at 14 11 03](https://user-images.githubusercontent.com/8957346/55683353-04cf0a80-593f-11e9-8650-e27bafa13458.png)

**Comment by mgamsjager** [comment]
Sp why close this one? `procps ` does not exist on FreeBSD. So the work around does not work.
I plan to do a PR to fix this in a proper way.

**Comment by mgamsjager** [comment]
https://github.com/cjbassi/gotop/pull/143

**Comment by cjbassi** [comment]
Assuming #143 fixed the process list issue, we just have the empty temperatures list now. Although it also looks like there's an issue getting information about Swap usage in the Memory Usage graph.

Btw, are you running gotop in a FreeBSD jail in the image? Looks like that might be the case from Disk Usage listing. I'm not super familiar with jails but I wonder if that would affect anything.

**Comment by mgamsjager** [comment]
> Assuming #143 fixed the process list issue, we just have the empty temperatures list now. Although it also looks like there's an issue getting information about Swap usage in the Memory Usage graph.
> 
> Btw, are you running gotop in a FreeBSD jail in the image? Looks like that might be the case from Disk Usage listing. I'm not super familiar with jails but I wonder if that would affect anything.

I can have a look at those 2 issues as well.

**Comment by herrbischoff** [comment]
No, this was running directly on the host system.

**Comment by mgamsjager** [comment]
https://github.com/cjbassi/gotop/pull/145 fixes the temperature, small fix for the process list and adds basis swap info

**Comment by cjbassi** [comment]
So does #145 fix everything here then? @herrbischoff Can you test that things are working for you using the latest commits?

**Comment by herrbischoff** [comment]
Indeed. This looks promising. Temperatures could be more fine-grained but that's most definitely a FreeBSD driver issue. So, all is good on my end. I'm closing this.

<img width="1440" alt="Screenshot 2019-06-04 at 13 35 50" src="https://user-images.githubusercontent.com/8957346/58876264-d2872280-86cd-11e9-8df0-e8fef0220917.png">
