### ISSUE TITLE
Downloading w/ Go Get

### ISSUE THREAD

**Issue by maxdobeck** [cjbassi/gotop#139]
This is a beautiful project by the way.  awesome stuff :+1: 

But when I try and install w/ go get nothing happens: `go get -u github.com/cjbassi/gotop`.  I mean the packages downlad and etc 
```
go: finding github.com/cjbassi/gotop latest
go: finding github.com/gizak/termui/v3 v3.0.0
go: finding github.com/StackExchange/wmi v0.0.0-20180116203802-5d049714c4a6
go: finding github.com/distatus/battery v0.9.0
go: finding github.com/go-ole/go-ole v1.2.1
go: finding github.com/mitchellh/go-wordwrap v1.0.0
go: finding github.com/shirou/w32 v0.0.0-20160930032740-bb4de0191aa4
go: finding howett.net/plist v0.0.0-20181124034731-591f970eefbb
go: finding github.com/stretchr/testify v1.3.0
go: finding github.com/shirou/gopsutil v2.18.11+incompatible
go: finding golang.org...
```

`My version: go version go1.12.1 linux/amd64` but essentialy after I run go get I can't cd to `...github.com/cjbassi/gotop`.  Ther's just no cbassi file.

**Comment by cjbassi** [comment]
Looks like you have a typo when trying to cd, since its `cjbassi` and not `cbassi`. :) Let me know if that fixes it or not.

**Comment by maxdobeck** [comment]
That was a typo in my write-up! I think this is a "me" issue as I was messing around with go.mod stuff. I think this can be closed after doing some additional googling. 

Normally I just expect the packages to be in the GitHub/username space after running go get but nothing was being created

**Comment by cjbassi** [comment]
For me, doing `go get github.com/cjbassi/gotop` downloads the repo to `$GOPATH/src/github.com/cjbassi/gotop` and builds the binary at `$GOPATH/bin/gotop`. The one caveat is that you can't `go get` when you're in the directory of a go module, cause then it installs the package as a go module dependency instead of installing globally. Otherwise, it might be an issue with your `$GOPATH`.

**Comment by maxdobeck** [comment]
Go Modules confused me as I'm not particularly clever.  Had `GO111MODULE=on` and basically `go get` doesn't do anything if you're in the GOPATH while go getting.  Resolved by reverting go111module to auto.  :+1: my problem but thanks!
