### ISSUE TITLE
usage's dont show the nice looking dots

### ISSUE THREAD

**Issue by picarica** [cjbassi/gotop#159]
![replace](https://user-images.githubusercontent.com/45492894/61816419-9e69eb80-ae4c-11e9-85da-0f5430bf4363.png)

Required information:

- gotop version (3.0.0):
- The output of `uname -a`: Linux Beast 5.1.5-gentoo #1 SMP Tue May 28 21:14:04 CEST 2019 x86_64 AMD FX-8370 Eight-Core Processor AuthenticAMD GNU/Linux
- Terminal emulator (e.g. iTerm or gnome terminal): rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
- Any relevenat hardware info: using Gentoo ?
- tmux version if using tmux:nope

Also please copy or attach `~/.local/state/gotop/errors.log` if it exists and contains logs:
error log is empty

**Comment by cjbassi** [comment]
Yah this is a known issue. Check out #18 for some possible solutions.
