### ISSUE TITLE
gotop show logs and exit 

### ISSUE THREAD

**Issue by suconghou** [cjbassi/gotop#16]
* Operating System : macOS 10.13.3 (17D102)
* CPU architecture : Darwin MacBookPro 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
* zsh
* Using tmux? no 
* use download script 

run gotop it only shows logs and exited
```
2018/04/10 13:54:01 
self.Count: 8
gopsutil.Counts(): 8
len(percents): 0
percents: []
```

**Comment by cjbassi** [comment]
A bunch of people were getting a weird issue so I just added some logging to it which is what you're seeing. It looks like gopsutil is having some issues returning CPU usage information so I'll have to check over there and get back to you.

**Comment by cjbassi** [comment]
For those having issues, you can use `go get` to build from source which should fix the issue for now.

**Comment by suconghou** [comment]
yes , it fixed , but the startup is too slow, about half a minute, and cpu usage is high, about 18% on macbook pro Intel Core i7

**Comment by cjbassi** [comment]
Going to close this issue and create a new one combining the issues on OSX since people have been having a bunch of them.

**Comment by cjbassi** [comment]
gotop should be working on OSX now, and you can install using either Git, Homebrew, or from Source as documented in the readme. Let me know if you're still having any issues!
