### ISSUE TITLE
Battery percentage discrepancy - macOS

### ISSUE THREAD

**Issue by damonallison** [cjbassi/gotop#160]
The battery percentage shown in `gotop` differs from what macOS shows in the menu bar.

It does match the underlying `distatus/battery` value (`bat.Current/bat.Full*100,`) correctly. I'm not sure if there are any other options that would mimic the menu bar consistently (or if you'd even want to do that - the values from `distatus/battery` are more accurate).

Perhaps all that is needed is a comment in the documentation stating the difference.

Thanks for all your work w/ `gotop`!

<img width="241" alt="battery-macos" src="https://user-images.githubusercontent.com/32421/62863975-0edb8e00-bcd0-11e9-8f3f-8d6cf529de3e.png">

**Comment by whuang8** [comment]
I am seeing a 5% discrepancy on my mac as well. I think this issue might make more sense as an open [distatus/battery issue](https://github.com/distatus/battery/issues) rather than a gotop issue since we know gotop's battery percentage comes directly from the `battery` pkg.

**Comment by damonallison** [comment]
I agree. `gotop` is using the right values from `battery`. I'm going to close this issue, look into `battery`, and will file a ticket there as appropriate.
