### ISSUE TITLE
CPU Usage only shows AVRG

### ISSUE THREAD

**Issue by chrisco23** [cjbassi/gotop#162]
Thanks for this nice tool.

On my XPS-15 (i7), under CPU Usage I only see AVRG, not indivual CPUs.

This is a fully updated Arch Linux system.

Am I missing something?

**Comment by karuboniru** [comment]
Try `-p, --percpu`

**Comment by chrisco23** [comment]
That was what I missed.  Thanks, seems to work perfectly!
