### ISSUE TITLE
from "yay", gotop-bin works but gotop and gotop-git failed to build

### ISSUE THREAD

**Issue by chrisco23** [cjbassi/gotop#163]
On my Arch Linux system, using "yay" to install, I tried first gotop, then gotop-git, and both gave me the following, before I tried gotop-bin which worked fine thankfully.

build github.com/cjbassi/gotop: cannot load bufio: open /home/mylinuxuser/.cache/yay/gotop-git/src/gotop-git/vendor/bufio: no such file or directory

Any ideas?  Thanks.

**Comment by zicklam** [comment]
I am using `yay v9.2.1` on Arch Linux and worked for me to install gotop-3.0.0-3

Which go version you are running?

**Comment by chrisco23** [comment]
thx seems to me this issue has resolved itself at some point, so will close.

for the record though, current working situation:

```
$ go version
go version go1.13.1 linux/amd64

$ gotop --version
3.0.0

$ yay --version
yay v9.3.3.r7.g6e2a4de - libalpm v11.0.3
```
There is a separate issue where gotop still doesn't for me separate by CPUs, but again, that's a separate issue, closing.
