### ISSUE TITLE
Cannot quit gotop on FreeBSD

### ISSUE THREAD

**Issue by daniejstriata** [cjbassi/gotop#190]
I'm not able to quit from gotop on FreeBSD using CTRL -c c or 'q'
I have to close the terminal to quit.

Required information:

- gotop version (`gotop -V`): 3.5.2
- The output of `uname -a`: FreeBSD grbl-ffpf.global.test.lan 11.3-RELEASE-p7 FreeBSD 11.3-RELEASE-p7 #0: Tue Mar 17 08:32:23 UTC 2020     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
- Terminal emulator (e.g. iTerm or gnome terminal): GNOME Terminal
- Any relevenat hardware info:
- tmux version if using tmux: not installed

`~/.local/state/gotop/errors.log`
11:43:30 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:43:30 temp.go:18: error updating temp for CPU 0 : exit status 1
11:43:35 temp.go:18: error updating temp for CPU 0 : exit status 1
11:43:35 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:43:40 temp.go:18: error updating temp for CPU 0 : exit status 1
11:43:40 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:43:45 temp.go:18: error updating temp for CPU 0 : exit status 1
11:43:45 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:43:50 temp.go:18: error updating temp for CPU 0 : exit status 1
11:43:50 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:43:55 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:43:55 temp.go:18: error updating temp for CPU 0 : exit status 1
11:44:00 temp.go:18: error updating temp for CPU 0 : exit status 1
11:44:00 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:44:05 temp.go:18: error updating temp for CPU 0 : exit status 1
11:44:05 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:44:10 temp.go:18: error updating temp for CPU 0 : exit status 1
11:44:10 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:44:15 temp.go:18: error updating temp for CPU 0 : exit status 1
11:44:15 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:44:20 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:44:20 temp.go:18: error updating temp for CPU 0 : exit status 1
11:44:25 temp.go:18: error updating temp for CPU 0 : exit status 1
11:44:25 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:44:30 temp.go:18: error updating temp for CPU 0 : exit status 1
11:44:30 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:44:35 temp.go:18: error updating temp for CPU 0 : exit status 1
11:44:35 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:44:40 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:44:40 temp.go:18: error updating temp for CPU 0 : exit status 1
11:44:45 temp.go:18: error updating temp for CPU 0 : exit status 1
11:44:45 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:44:50 temp.go:18: error updating temp for CPU 0 : exit status 1
11:44:50 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:44:55 temp.go:18: error updating temp for CPU 0 : exit status 1
11:44:55 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:45:00 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:45:00 temp.go:18: error updating temp for CPU 0 : exit status 1
11:45:05 temp.go:18: error updating temp for CPU 0 : exit status 1
11:45:05 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:45:10 temp.go:18: error updating temp for CPU 0 : exit status 1
11:45:10 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:45:15 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:45:15 temp.go:18: error updating temp for CPU 0 : exit status 1
11:45:20 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:45:20 temp.go:18: error updating temp for CPU 0 : exit status 1
11:45:25 temp.go:18: error updating temp for CPU 0 : exit status 1
11:45:25 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:45:30 temp.go:18: error updating temp for CPU 0 : exit status 1
11:45:30 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:45:35 temp.go:18: error updating temp for CPU 0 : exit status 1
11:45:35 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:45:40 temp.go:18: error updating temp for CPU 0 : exit status 1
11:45:40 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:45:45 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:45:45 temp.go:18: error updating temp for CPU 0 : exit status 1
11:45:50 temp.go:18: error updating temp for CPU 0 : exit status 1
11:45:50 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:45:55 temp.go:18: error updating temp for CPU 0 : exit status 1
11:45:55 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:46:00 temp.go:18: error updating temp for CPU 0 : exit status 1
11:46:00 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:46:05 temp.go:18: error updating temp for CPU 0 : exit status 1
11:46:05 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:46:10 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:46:10 temp.go:18: error updating temp for CPU 0 : exit status 1
11:46:15 temp.go:18: error updating temp for CPU 0 : exit status 1
11:46:15 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:46:20 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:46:20 temp.go:18: error updating temp for CPU 0 : exit status 1
11:46:25 temp.go:18: error updating temp for CPU 0 : exit status 1
11:46:25 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:46:30 temp.go:18: error updating temp for CPU 0 : exit status 1
11:46:30 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:46:35 temp.go:18: error updating temp for CPU 0 : exit status 1
11:46:35 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:46:40 temp.go:18: error updating temp for CPU 0 : exit status 1
11:46:40 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:46:45 temp.go:18: error updating temp for CPU 0 : exit status 1
11:46:45 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:46:50 temp.go:18: error updating temp for CPU 0 : exit status 1
11:46:50 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:46:55 temp.go:18: error updating temp for CPU 0 : exit status 1
11:46:55 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:47:00 temp.go:18: error updating temp for CPU 0 : exit status 1
11:47:00 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:47:05 temp.go:18: error updating temp for CPU 0 : exit status 1
11:47:05 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:47:10 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:47:10 temp.go:18: error updating temp for CPU 0 : exit status 1
11:47:15 temp.go:18: error updating temp for CPU 0 : exit status 1
11:47:15 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:47:20 temp.go:18: error updating temp for CPU 0 : exit status 1
11:47:20 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:47:25 temp.go:18: error updating temp for CPU 0 : exit status 1
11:47:25 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:47:30 temp.go:18: error updating temp for CPU 0 : exit status 1
11:47:30 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:47:35 temp.go:18: error updating temp for CPU 0 : exit status 1
11:47:35 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:47:40 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:47:40 temp.go:18: error updating temp for CPU 0 : exit status 1
11:47:45 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:47:45 temp.go:18: error updating temp for CPU 0 : exit status 1
11:47:50 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:47:50 temp.go:18: error updating temp for CPU 0 : exit status 1
11:47:55 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:47:55 temp.go:18: error updating temp for CPU 0 : exit status 1
11:48:00 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:48:00 temp.go:18: error updating temp for CPU 0 : exit status 1
11:48:05 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:48:05 temp.go:18: error updating temp for CPU 0 : exit status 1
11:48:10 temp.go:18: error updating temp for CPU 0 : exit status 1
11:48:10 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:48:15 temp.go:18: error updating temp for CPU 0 : exit status 1
11:48:15 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:48:20 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:48:20 temp.go:18: error updating temp for CPU 0 : exit status 1
11:48:25 temp.go:18: error updating temp for CPU 0 : exit status 1
11:48:25 temp.go:18: error updating temp for Thermal zone 0: exit status 1
11:48:30 temp.go:18: error updating temp for CPU 0 : exit status 1
11:48:30 temp.go:18: error updating temp for Thermal zone 0: exit status 1

**Comment by xxxserxxx** [comment]
Hiya @daniejstriata -- you have the wrong repo.  @cjbassi stopped active development on this repository a while ago, and I've continued in [mine](https://github.com/xxxserxxx/gotop).  v3.5.2 is from my repository.  Can you tell me where you got this URL from?  If there's an outdated reference, I'd like to see if I can get it fixed.

This was also [reported yesterday](https://github.com/xxxserxxx/gotop/issues/95) by @yurivict, who says that none of the hotkeys are working for him on FreeBSD.  Since they're working on OSX and Linux, I'm putting it down to a platform-related issue, and will look into it this weekend when I have time to set up a FreeBSD VM.

You are also seeing some sensor issues -- would you please log that as a separate ticket, again on my fork?  That's unrelated to the hotkey issue, but those errors shouldn't be happening like that.

Thanks

**Comment by daniejstriata** [comment]
Thank you. I did not realise but did notice the missing version :-) I got here from a Google search for gotop.

I'll pop over to your repo and upload the log entries there.

**Comment by yurivict** [comment]
Duplicate of https://github.com/xxxserxxx/gotop/issues/95
