### ISSUE TITLE
Lines glitch in Konsole terminal

### ISSUE THREAD

**Issue by cyruzin** [cjbassi/gotop#191]
I'm using Arch Linux with LTS kernel and KDE, the terminal is Konsole. How can I fix this?

![image](https://user-images.githubusercontent.com/2396581/81960812-e3cbf500-95e7-11ea-98ac-f188e40af7e7.png)

**Comment by xxxserxxx** [comment]
@cyruzin, can you please re-open this in https://github.com/xxxserxxx/gotop?  This project branch is no longer maintained.  Thanks.

**Comment by cyruzin** [comment]
Sure.
