### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by cjbassi** [cjbassi/gotop#23]
Some people have been having slow startups so I created an issue for it.

If you feel inclined to provide some debugging info and have the Go toolchain set up,  you can:
```
go get github.com/cjbassi/gotop
# move into the repo
git checkout slow-startup
go run main.go
```

gotop should print some numbers. If gotop stays on a number for a while, let me know:

* which one it is
* how long it stays there
* what your OS is
* whether gotop does eventually display normally

Thanks!

**Comment by pkieltyka** [comment]
staying on number 12 for a while. im on MacOS 10.13

**Comment by cjbassi** [comment]
@pkieltyka Like how many seconds?

**Comment by cjbassi** [comment]
Could you try the latest release and let me know if it loads this time? If it does, does the Process Table load too?

**Comment by cjbassi** [comment]
Actually if you could pull the latest commits from the slow-startup branch and run that again and then let me know where it gets stuck that would be great.

**Comment by embano1** [comment]
OSX 10.12.6
Stays roughly 40s at:

```bash
$ go run main.go
1
2
3
4
5
6
7
```

**Comment by Vic020** [comment]
macOS 10.13.3 
25s
and have nothing on Temperatures

```
╰─$ go run main.go
1
2
3
4
5
6
7
```

**Comment by cjbassi** [comment]
@Vic020 The temperatures widget doesn't have any text in it at all?

Also could you pull the latest changes to the slow-startup branch and try that again? And also try the latest release and let me know if anything changes? Make sure it's version `1.2.11`. You have to pull the new `download.sh` script to get the new release. Thanks!

**Comment by Vic020** [comment]
Yes, The temperatures widget doesn't have any text in it at all !

nothing changed after pulled the latest code, it would take 20-30s to launch.
```
$ go run main.go
1
2
3
4
5
6
7
```

Got panic after used new script, and version is **1.2.12**
```
$ ./gotop
Error caught. Exiting program.

Issue with CPU percentages.

Diagnostics:
self.Count: 4
gopsutil.Counts(): 4
len(percents): 0
percents: []
self.interval: 1s

panic: 1

goroutine 33 [running]:
github.com/cjbassi/gotop/utils.Error(0x1184197, 0xf, 0xc42017c060, 0x52)
	/home/cjbassi/go/src/github.com/cjbassi/gotop/utils/utils.go:30 +0x23f
github.com/cjbassi/gotop/widgets.(*CPU).update(0xc420154000)
	/home/cjbassi/go/src/github.com/cjbassi/gotop/widgets/cpu.go:57 +0x532
created by github.com/cjbassi/gotop/widgets.NewCPU
	/home/cjbassi/go/src/github.com/cjbassi/gotop/widgets/cpu.go:38 +0x2d3
```
macOS 10.13.3
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)

**Comment by samling** [comment]
Hanging on number 7 for me as well for about 6-7 seconds. Gotop does load as soon as it gets past number 7, however I also don't have temperatures. Running MacOS 10.12.6.

**Comment by AlphaWong** [comment]
Is it related to go version as seems go 1.10 has a performance issue ?
Is it build by go 1.10 or go 1.9 ?

Might be related ?
https://github.com/golang/go/issues/24034

**Comment by f1337** [comment]
Hangs on step 7 for 5-6 seconds.

Probably unrelated, but once loaded, this version pegs my CPUs at 99%. Neither this version, nor `master` shows me temperature data.

My system details:
macOS High Sierra 10.13.4
MacBook Pro (Retina, 15-inch, Mid 2015)
Processor: 2.5 GHz i7
Memory: 16 GB
Terminal: iTerm2 + fish shell + ohmyfish. no tmux.
Go: 1.10.1 darwin/amd64 (via `brew install go`)

**Comment by cjbassi** [comment]
Thanks for all the info and sorry people have been having issues. It turns out gopsutil has some issues on OSX which makes gotop unusable on OSX right now. Hoping to fix that in the future, but I also don't have a mac to test on right now so idk how long it will take. Going to close this issue and open another one that pools the issues people have been having on OSX.

**Comment by cjbassi** [comment]
gotop should be working on OSX now, and you can install using either Git, Homebrew, or from Source as documented in the readme. Let me know if you're still having any issues! Thanks @f1337 for helping get it to work!
