### ISSUE TITLE
Panic: Issue with CPU percentages

### ISSUE THREAD

**Issue by dmonay** [cjbassi/gotop#24]
**Data**:
Gotop version: 1.2.11
MacOS 10.12.6
Darwin Kernel Version 16.7.0: Tue Jan 30 11:27:06 PST 2018;
root:xnu-3789.73.11~1/RELEASE_X86_64 x86_64

Shell is bash

Terminal is iTerm

Not using tmux

**Error**:
```
Error caught. Exiting program.

Issue with CPU percentages.

Diagnostics:
self.Count: 8
gopsutil.Counts(): 8
len(percents): 0
percents: []
self.interval: 1s

panic: 1

goroutine 15 [running]:
github.com/cjbassi/gotop/utils.Error(0x11841d7, 0xf, 0xc42001e4e0, 0x52)
	/home/cjbassi/go/src/github.com/cjbassi/gotop/utils/utils.go:30 +0x23f
github.com/cjbassi/gotop/widgets.(*CPU).update(0xc42000b020)
	/home/cjbassi/go/src/github.com/cjbassi/gotop/widgets/cpu.go:57 +0x532
created by github.com/cjbassi/gotop/widgets.NewCPU
	/home/cjbassi/go/src/github.com/cjbassi/gotop/widgets/cpu.go:38 +0x2d3
```

**Comment by moshemarciano** [comment]
same here, macos 10.12.6

**Comment by cjbassi** [comment]
Can you try building/running from source and seeing if you still get the error? Thanks.

**Comment by dmonay** [comment]
That worked.

**Comment by moshemarciano** [comment]
So installing via homebrew is broken?

also, after doing

brew uninstall --force gotop
go get -u github.com/cjbassi/gotop
gotop

it does work, but very slow to open (5 seconds) and then it utilizes 100% of the CPU

**Comment by dmonay** [comment]
I did not install over homebrew - I installed using `download.sh` script.

**Comment by cjbassi** [comment]
gotop should be working on OSX now, and you can install using either Git, Homebrew, or from Source as documented in the readme. Let me know if you're still having any issues!

**Comment by dmonay** [comment]
Can confirm that gotop is no longer spinning up the fans on MacOS. Installed from Homebrew.

One issue I noticed is that the process path is getting cut off:
<img width="848" alt="screen shot 2018-05-25 at 1 10 26 pm" src="https://user-images.githubusercontent.com/5934549/40557149-b55b4698-603e-11e8-93c4-07edb30e21f3.png">

**Comment by cjbassi** [comment]
Yah that's cause `ps` is trimming the command name for some reason. Will play around with it and get back to you.

**Comment by cjbassi** [comment]
Can you try either running [this](https://github.com/cjbassi/gotop/files/2070135/gotop.zip) exe, or running the `command-name-darwin` branch with the go tools and let me know if it works? Thanks.
