### ISSUE TITLE
Theme directory?

### ISSUE THREAD

**Issue by boubounokefalos** [cjbassi/gotop#30]
Maybe a silly question but where do I need to save a *.go theme configuration, in order to make it available on gotop?

**Comment by cjbassi** [comment]
Themes go in the [colorschemes](https://github.com/cjbassi/gotop/tree/master/colorschemes) folder. There's some in there you can use for reference, with additional guidance in the comment at the top of the the [template](https://github.com/cjbassi/gotop/blob/master/colorschemes/template.go) file. Let me know if you have any trouble with it!
