### ISSUE TITLE
Process grouping not working

### ISSUE THREAD

**Issue by chneau** [cjbassi/gotop#31]
Make sure gotop is updated and the issue still persists before creating an issue.
Check current version with `gotop -v` and check the latest version from the releases tab on GitHub.
```bash
11:39:43-c@d:~$gotop -v
1.2.14
```
Please give the following info when creating an issue:
* The output of `uname -a`
```
11:39:46-c@d:~$uname -a
Linux d 4.13.0-39-generic #44~16.04.1-Ubuntu SMP Thu Apr 5 16:43:10 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
* Terminal shell (like zsh or bash)
`bash`
* Terminal emulator (like iTerm or gnome terminal)
`ubuntu default terminal`
* Using tmux?
`nope`

![image](https://user-images.githubusercontent.com/5753629/39866093-13c1dc00-5447-11e8-9a14-a6d8fbc91228.png)

I expected to see all chromium-browser (Which is the blue "Chrome" you can get with apt get, not the yellow "Chrome" from google ...) grouped in one line.   (This is what I'm use to, but not sure if it's the standard or something specific to the system)
(I'll comment the another result I have on another computer)
(Not sure what is kworker but it could be grouped too ? maybe it's wiser/ more interesting not to group kworkers i'm not sure ???)

**Comment by chneau** [comment]
```bash 
11:46:47-c@c:~/go/src/github.com/cjbassi/gotop$gotop -v
1.2.14
11:46:50-c@c:~/go/src/github.com/cjbassi/gotop$uname -a
Linux c 4.13.0-41-generic #46~16.04.1-Ubuntu SMP Thu May 3 10:06:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
Here is what I see on another computer (But this one is using Google Chrome (yellow), not Chromium thing (blue))

![image](https://user-images.githubusercontent.com/5753629/39866319-128c31d6-5448-11e8-9b47-8357767041a3.png)

Here you can see `count: 19, command: chrome`

**Comment by cjbassi** [comment]
What happens when you press `tab`? Do the processes get grouped? Processes are supposed to be grouped by default, but you can toggle it on and off with `tab`. So maybe something caused gotop to start with processes ungrouped.

Looks like CPU% and Mem% formatting are off too, supposed to be only 1 decimal space. Plus you were having that other issue from a while ago so something must be going on under the hood to be causing all theses issues XD

**Comment by chneau** [comment]
Hello @cjbassi , I'm sorry I can't reproduce this since I installed a windows on my laptop. Everything is working fine on my computer where there is an Ubuntu 16.04.

**Comment by cjbassi** [comment]
No worries, I'm just gonna close this but let me know if anything else comes up.
