### ISSUE TITLE
Show I/O usage in terms of data transfer, not how much space is taken (optionally?)

### ISSUE THREAD

**Issue by YurySolovyov** [cjbassi/gotop#32]
Title pretty much says it all.

**Comment by YurySolovyov** [comment]
FWIW: this is duplicate of https://github.com/cjbassi/gotop/issues/19/. My bad

**Comment by cjbassi** [comment]
I changed the Disk Usage widget and added i/o to the latest release. It's a little hidden so let me know if it works for you or if it should be tweaked.
