### ISSUE TITLE
EPYC/ZEN CPUs not supported ?

### ISSUE THREAD

**Issue by abucodonosor** [cjbassi/gotop#34]
Hello,

I'm testing gotop 1.3.0 ( gotop_1.3.0_linux_amd64.tgz )
I noticed on my EPYC Server it won't show any CPU in  
the CPU widgets while is fine on my Intel boxes.

The box has 2 * 16C/32T CPUs installed.

```
getconf _NPROCESSORS_ONLN
64

```
![epyc_64c_box](https://user-images.githubusercontent.com/18563759/40457668-04ef31ee-5ef8-11e8-9373-6ca90bc3c193.png)

* The output of `uname -a`

``` 
Linux ant 4.16.11-fw1 #1 SMP PREEMPT Tue May 22 21:17:26 CEST 2018 x86_64 AMD EPYC 7281 16-Core Processor AuthenticAMD GNU/Linux

```
* Terminal shell (like zsh or bash)

```
$ echo $SHELL
/bin/bash

```

* Terminal emulator (like iTerm or gnome terminal)

```
konsole -> ssh -> server ( cli )

```

* Using tmux?

```
No
```

Also k10temp is wrong on ZEN .. Each CPU has 4 dies and each die a temp
meaning on 2 soket box we get 8 different temperatures not just one.

eg this:

```
k10temp-pci-00e3
Adapter: PCI adapter
temp1:        +20.5°C  (high = +70.0°C)

k10temp-pci-00d3
Adapter: PCI adapter
temp1:        +20.8°C  (high = +70.0°C)

k10temp-pci-00c3
Adapter: PCI adapter
temp1:        +23.5°C  (high = +70.0°C)

k10temp-pci-00fb
Adapter: PCI adapter
temp1:        +19.8°C  (high = +70.0°C)

k10temp-pci-00eb
Adapter: PCI adapter
temp1:        +20.5°C  (high = +70.0°C)

k10temp-pci-00db
Adapter: PCI adapter
temp1:        +20.2°C  (high = +70.0°C)

k10temp-pci-00cb
Adapter: PCI adapter
temp1:        +20.1°C  (high = +70.0°C)

k10temp-pci-00f3
Adapter: PCI adapter
temp1:        +19.0°C  (high = +70.0°C)

```

If you need more infos please let me know.

Regards

**Comment by abucodonosor** [comment]
@cjbassi 

btw why CPUs are limited to 8 in that widget ? Because the graphs lines looks
strange for >8 ? 

Well even when that is wrong. Then your logic should be:

get_all_online_cpus() sort function
   if CPU.count <=8
            do_stuff_like_now_including_graphs_lines
    else ..
        display_all_cpus_without_graph_lines ( eg: just CPUx X% usage )

Limiting to 8 is somewhat starge these days if you consider one can have a workstation
with 128C up just easy.

But also 'normal' CPUs have 8C/16T , 16C/32T or 14C/28T etc .. 
so 8 is way to low these days

**Comment by cjbassi** [comment]
Yah it's mainly because the graph gets too congested with more than 8 lines.

As far as the CPU and Temp issues go, that would be an issue with a library I'm using called gopsutil for getting system information. I'll have to create an issue in that repo and go from there.

**Comment by cjbassi** [comment]
Hi, so the good people over at gopsutil would like some information to help fix this. Could you check out https://github.com/shirou/gopsutil/issues/568 and see if you can get them the information they need?

**Comment by abucodonosor** [comment]
@cjbassi 

Thx for the reminder , I really forgot about this one.

I've added now requested info to https://github.com/shirou/gopsutil/issues/568

**Comment by cjbassi** [comment]
@abucodonosor Could you try running gotop from the master branch with `gotop -p` and see if it gives you a CPU graph? I might have made a mistake and thinks might actually be working fine, so if you could test that that, that would be great.

**Comment by abucodonosor** [comment]
@cjbassi 
sure I'll do that once I'm back home and let you know .

**Comment by abucodonosor** [comment]
I did that quick from work ..

Thinks looks better in master first CPU seems to be detected now.

![gotop1](https://user-images.githubusercontent.com/18563759/49792948-40ace700-fd34-11e8-8bc0-958f7385665f.png)

**Comment by abucodonosor** [comment]
Well I have to test/look closer once I'm home.

But first issue will be 16 from 64 CPUs are just there.

However now seems ZEN(EPYC/RYZEN) work so maybe want me to 
open some other bug reports about these ?

**Comment by cjbassi** [comment]
Only 16 labels are shown because that's all that can fit, but all the graph lines should be there. So that's intentional behavior and not a bug.

**Comment by abucodonosor** [comment]
@cjbassi 

in this case you can close this .. 

But I would still like to open at least some feature request for this kind issue.

CPU / graph stuff can be split as example.
Or add option to show all CPUs just with % usage no other stuff.

**Comment by abucodonosor** [comment]
@cjbassi 

AMD ROME is coming with these max CPUs will grow again.

ROME will be s4 platform meaning max CPUs can be 4*64*2  ..

**Comment by cjbassi** [comment]
Yah feel free to open another issue. One idea is to only show the CPU widget, which should give you more real estate. There's the `-m` option which should help too.
