### ISSUE TITLE
segmentation violation on arch linux

### ISSUE THREAD

**Issue by iXo** [cjbassi/gotop#39]
Hi, gotop is crashing on my computer, I am using Arch Linux :

> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x50f86f]
> 
> goroutine 26 [running]:
> github.com/cjbassi/gotop/src/widgets.(*Disk).update(0xc420220000)
> 	/home/cjbassi/go/src/github.com/cjbassi/gotop/src/widgets/disk.go:90 +0x66f
> github.com/cjbassi/gotop/src/widgets.NewDisk(0x0)
> 	/home/cjbassi/go/src/github.com/cjbassi/gotop/src/widgets/disk.go:42 +0x195
> main.initWidgets.func5()
> 	/home/cjbassi/go/src/github.com/cjbassi/gotop/main.go:214 +0x22
> created by main.initWidgets
> 	/home/cjbassi/go/src/github.com/cjbassi/gotop/main.go:213 +0xda

Please give the following info when creating an issue:
* gotop -v : 1.4.0
* uname -a : Linux ixo-dev 4.16.8-1-ARCH #1 SMP PREEMPT Wed May 9 11:25:02 UTC 2018 x86_64 GNU/Linux
* Terminal shell : bash
* Terminal emulator : gnome terminal
* Using tmux : no

**Comment by iXo** [comment]
Could it be do to the fact that I have a drive with a name containing space (and is displayed as \040) ?

![capture du 2018-06-12 14-33-42](https://user-images.githubusercontent.com/401900/41290752-1cc37c84-6e4e-11e8-893e-1bb9a10ebcc2.png)

**Comment by cjbassi** [comment]
Yah so `usage` shouldn't be nil, which means that there's something wrong with the function call here
https://github.com/cjbassi/gotop/blob/fa70da84a3624a31095fe7f1d89f9bd2a71e8be6/src/widgets/disk.go#L89
and it's probably caused by an issue with `Part.Mount`, most likely with the space in the mount point. I'll check it out a bit more and get back to you about anything I find.

**Comment by Mange** [comment]
Same issue here.

```
› lsblk
NAME           MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sda              8:0    0 931.5G  0 disk  
└─sda1           8:1    0 931.5G  0 part  /run/media/mange/Mange Backup
nvme0n1        259:0    0 465.8G  0 disk  
├─nvme0n1p1    259:1    0   512M  0 part  /boot/efi
├─nvme0n1p2    259:2    0   488M  0 part  /boot
└─nvme0n1p3    259:3    0 464.8G  0 part  
  └─cryptoluks 254:0    0 464.8G  0 crypt 
    ├─vg0-swap 254:1    0    35G  0 lvm   [SWAP]
    ├─vg0-root 254:2    0 129.6G  0 lvm   /
    └─vg0-home 254:3    0 300.2G  0 lvm   /home
```

Partition names with spaces in them are very common, and they get mounted automatically by udisks.

**Comment by cjbassi** [comment]
Can you try updating to latest build (1.4.1) and letting me know if it's working? Just pushed some changes and they're working for me.

**Comment by Mange** [comment]
Works perfectly for me! Thank you!
