### ISSUE TITLE
Parasitic display

### ISSUE THREAD

**Issue by SebastienAuvray** [cjbassi/gotop#40]
Hello,

When running gotop on a fresh terminal, I get stdout & stderr coming from other processes ; these text offset all gotop display, therefore making it unuseful.
Any idea to skip these (maybe redirect other process, or totally refresh gotop each time) ?

Thank you,

Sébastien.

**Comment by cjbassi** [comment]
Can you try running gotop and piping stdout and stderr to a file and letting me know if that fixes things and also what the text is?

To pipe stdout/stderr to a file, you can do `gotop &> filename`.

**Comment by cjbassi** [comment]
Gonna close this buy let me know if you're having any issues still and I can try to help.

**Comment by SebastienAuvray** [comment]
Hi!
Sorry I didn’t answer to your request (sending gotop output to file).
We fixed it by redirecting all of our processes outputs, so no erratic output displays into ggotop’s one any more.

Thanx,

Sébastien.
