### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by necronoise** [cjbassi/gotop#41]
Hi dev! So, I just updated my distro and this bug happen with gotop:

> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x50f86f]
> 
> goroutine 12 [running]:
> github.com/cjbassi/gotop/src/widgets.(*Disk).update(0xc42000d2c0)
> 	/home/cjbassi/go/src/github.com/cjbassi/gotop/src/widgets/disk.go:90 +0x66f
> github.com/cjbassi/gotop/src/widgets.NewDisk(0x0)
> 	/home/cjbassi/go/src/github.com/cjbassi/gotop/src/widgets/disk.go:42 +0x195
> main.initWidgets.func5()
> 	/home/cjbassi/go/src/github.com/cjbassi/gotop/main.go:214 +0x22
> created by main.initWidgets
> 	/home/cjbassi/go/src/github.com/cjbassi/gotop/main.go:213 +0xda

Looks like its the same bug that happen with this guy: https://github.com/cjbassi/gotop/issues/39
Heres my distro info:
Linux 4.14.52-1-MANJARO #1 SMP PREEMPT Tue Jun 26 15:24:31 UTC 2018 x86_64 GNU/Linux
Shell: bash
Terminal: urxvt
I have tmux but im not using it to see gotop.
gotop version 1.4.0.

Do I need to change the gotop code or inform manjaro devs?

**Comment by necronoise** [comment]
And now its simple running ok.
What.

**Comment by cjbassi** [comment]
Huh that's strange. Did you do anything different when it worked? And is it still working?

**Comment by necronoise** [comment]
I just updated my distro lol `sudo pacman -Syyuu`. Also I got the error again yesterday, I was so confused, I did the reboot and then the bug was gone.

**Comment by cjbassi** [comment]
So like the issue the other guy is having too, it looks to be an issue with Disk information. Can you run `lsblk` and copy the output here?

**Comment by necronoise** [comment]
Sure!
> NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
> sda      8:0    0 698,7G  0 disk 
> ├─sda1   8:1    0   100M  0 part 
> ├─sda2   8:2    0 360,9G  0 part 
> └─sda3   8:3    0 337,7G  0 part /
> sr0     11:0    1  1024M  0 rom  
> zram0  254:0    0 973,9M  0 disk [SWAP]

**Comment by cjbassi** [comment]
Just pushed some changes that fixed the issue for me, so if you update and let me know if you have any more issues that would be great.

**Comment by necronoise** [comment]
So, I dont know if this bug still on, because I dont get the issue anymore haha, but thank you for the work!

**Comment by cjbassi** [comment]
Sorry, just went ahead and closed this, but it should be fixed! It was caused by mounting a disk drive somewhere so that there was a space in the mount path.

**Comment by Arcandres** [comment]
Same error, If I umount my external drive It works normally.
Arch Linux 4.18.16
**Gotop** 1.5.0

**Comment by cjbassi** [comment]
@Arcandres Can you give me the output of `lsblk` with your drive mounted, the name of your drive, and any other info you can? The more info the better, like drive type (usb vs external disk) etc.

**Comment by Arcandres** [comment]
> @Arcandres Can you give me the output of `lsblk` with your drive mounted, the name of your drive, and any other info you can? The more info the better, like drive type (usb vs external disk) etc.

Yeah, the problem is with the partition name.
```
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0 111.8G  0 disk 
└─sda1   8:1    0 111.8G  0 part /
sdb      8:16   0 465.8G  0 disk 
├─sdb1   8:17   0 195.3G  0 part 
└─sdb2   8:18   0 269.5G  0 part /run/media/arcandres/Games & Software
```
Once I changed it, It works fine.
```
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0 111.8G  0 disk 
└─sda1   8:1    0 111.8G  0 part /
sdb      8:16   0 465.8G  0 disk 
├─sdb1   8:17   0 195.3G  0 part 
└─sdb2   8:18   0 269.5G  0 part /run/media/arcandres/Software
```

**Comment by cjbassi** [comment]
I tested this myself and confirmed that it was the space character again. I had thought this was fixed by the dependency causing the issue but apparently not, so I just re-added the fix that I applied last time and created a new release, but it should be working now.

**Comment by Arcandres** [comment]
Yeah, now It is working even with spaces in the partition name.
