### ISSUE TITLE
Panic: integer divide by zero

### ISSUE THREAD

**Issue by serussell** [cjbassi/gotop#44]
_Make sure gotop is updated and the issue still persists before creating an issue._
gotop was installed with the instructions:
```
brew tap cjbassi/gotop
brew install gotop
```

_Check current version with `gotop -v` and check the latest version from the releases tab on GitHub._
```
1006)~ % gotop -v
panic: runtime error: integer divide by zero
```

_Please give the following info when creating an issue:_
_* The output of `uname -a`_
```
1007)~ % uname -a
Darwin PHLLT8526.middleearth.home 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```

_* Terminal shell (like zsh or bash)_
```
1028)~ % $SHELL --version
zsh 5.4.2 (x86_64-apple-darwin17.3.0)
```

_* Terminal emulator (like iTerm or gnome terminal)_
iTerm2
Build 3.1.6

_* Using tmux?_
Absolutely!
```
1030)~ % tmux -V
tmux 2.6
```

**Comment by cjbassi** [comment]
Can you try running gotop without tmux and seeing if the issue still occurs? I think some people were having a similar issue before. Also if you could copy the stack trace or screenshot it if the terminal breaks then that would be great! Thanks.

**Comment by cjbassi** [comment]
Going to close this as part of housekeeping, but let me know if you run into this again.
