### ISSUE TITLE
Crash caused by table widget

### ISSUE THREAD

**Issue by cjbassi** [cjbassi/gotop#46]
![4lpxhid](https://user-images.githubusercontent.com/23287621/43601848-22f23f06-9643-11e8-9ee1-bdd3484b82b8.png)

**Comment by constb** [comment]
I just had the exact same issue. `gotop` was running in background ssh session in terminal for several hours, and then it wasn't…

**Comment by cjbassi** [comment]
Should be fixed with ff62b55133f5196031efcf9466ab022b8c11ffe4. Was caused by the process widget being read to and written to at the same time.
