### ISSUE TITLE
macOS: process name is cropped

### ISSUE THREAD

**Issue by saghul** [cjbassi/gotop#47]
See the image:

<img width="2027" alt="screen shot 2018-08-08 at 13 23 42" src="https://user-images.githubusercontent.com/317464/43834527-ad5a45b0-9b0e-11e8-9aa8-66b7ade2fc8d.png">

* The output of `uname -a`

`Darwin november 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
`

* Terminal shell (like zsh or bash)

bash

* Terminal emulator (like iTerm or gnome terminal)

iTerm

* Using tmux?

Nope

**Comment by cjbassi** [comment]
I pushed some changes to the `macos-cropped-processes` branch to try out.  You can run that from source if you have the `go` tools installed or you can run this binary that I built from that branch for macOS:
[gotop.zip](https://github.com/cjbassi/gotop/files/2272816/gotop.zip)

Let me know if anything changes or if there's any issues!

**Comment by saghul** [comment]
That was quick! So, here are the results: the build you linked works better because it seems to remote the full path to the process, so most of them fit, but some are still cropped.

> ps -caxo pid,comm,pcpu,pmem,args

This shows the same as the above binary.



> ps -axo pid,comm,pcpu,pmem,args

This shows the old (well, current) way, with the full path.

I wonder if exploring how htop does it could yield any useful info. Here is a screenshot where I selected to hide the path and highlight the basename of the program:

<img width="2027" alt="screen shot 2018-08-09 at 09 30 12" src="https://user-images.githubusercontent.com/317464/43884739-31d84212-9bb7-11e8-8b74-0da37feac4e0.png">

So, I assume we'd just want the basename.

Thanks again for your quick response and great project!

**Comment by cjbassi** [comment]
That's good it's just showing the basename now. That was another bug actually. When running that binary, if you press tab, does it still show the process basename or does it change to the full path?

So `ps` is really the only way to get process info on OSX, but it seems to be trimming its output. There's a few flags that are supposed to change the formatting and width but they don't seem to be doing anything on my machine. Couldn't find much by googling but checking out htop is a good idea.

**Comment by curiouscat2018** [comment]
Love this tool but this issue bugs me on Mac OS. Is the repo still maintained ?

**Comment by cjbassi** [comment]
Yes it's still maintained, I just don't have a mac to test on. Also this is actually an issue with `ps` since it's returning the cropped names. On linux I can do:
```ps -axo pid:10,comm:50,pcpu:5,pmem:5,args```
where the `:number` makes it so the content of the column doesn't get cropped below that width, but it wasn't working for people on osx. If you could play around with that and get back to me that would be great.

**Comment by cjbassi** [comment]
@VKoskiv Thanks, I just added the `-c` flag. Some other people were asking for that too.

So does specifying the column width with `:{number}` only work when the `-c` flag is set?

**Comment by VKoskiv** [comment]
@cjbassi The `man` entry `PS(1)` in the BSD manual says:

> -c      Change the ``command'' column output to just contain the executable name, rather than the full command line.

All it does is limit the output to show only the executable name.

**Comment by cjbassi** [comment]
Thanks. So then you're able to specify the column width with or without the `-c` option then? Can you paste the contents of `ps --version`?

**Comment by VKoskiv** [comment]
@cjbassi The macOS `ps` util doesn't have `--version`, so here's the whole manpage instead. It should contain all the needed info.

https://gist.github.com/VKoskiv/5e9d10b2b89688c21af4f5e55f0be9e5

**Comment by hadret** [comment]
@cjbassi `-ww` (full command I was trying `ps auxww`) doest the trick and piping it to a file makes no difference (lines are at full-width as expected).

**Comment by cjbassi** [comment]
Thanks, can you try `master` and let me know if it works now?

**Comment by hadret** [comment]
<img width="1552" alt="screenshot 2019-02-06 at 09 56 10" src="https://user-images.githubusercontent.com/470686/52330327-7fd67c00-29f5-11e9-8f8b-fe0fde44e6b3.png">

Looks better 👍

**Comment by cjbassi** [comment]
Yup that looks good! Glad we got it working. Going to close this and I'll also create a new release today.
