### ISSUE TITLE
Quantity Rounding

### ISSUE THREAD

**Issue by VGrol** [cjbassi/gotop#48]
```
* Kernel: Archlinux 4.17.12
* Terminal shell: Fish
* Terminal emulator: Termite
* Gotop version: 1.4.1
```

It appears that there is some kind of rounding error done on Gotops behalf.
I have a feeling that it defaults to GiB instead of the displayed GB. 
Either way, it results in more numbers being displayed than there actually are.

As an example, a 100GB partition is used for 22%, but claims to have 82GB free.
Another would be RAM, which is rounded up from 16GB to 17.

Other programs like Htop report this correctly under the same circumstances. 
If this is deliberate and it calculates GiB, I'd recommend changing the name or giving an option to tweak it.

**Comment by cjbassi** [comment]
Thanks for pointing that out, you were right, the conversions were from B to KiB, MiB etc. Just pushed a commit to `master` that fixes that. The Used% in the Disk Usage widget is derived from [gopsutil](https://github.com/shirou/gopsutil) tho, so maybe try the master branch and let me know if there's still an issue with that and I can fix that too.

**Comment by cjbassi** [comment]
Closing this but I'll reopen if there's any more issues.
