### ISSUE TITLE
Excessive panics/crashes

### ISSUE THREAD

**Issue by serussell** [cjbassi/gotop#49]
This was obviously done on purpose, as the definition of Error() throws a panic at the end.  What drove this design decision, rather than gracefully handling the error?

On both Mac and Linux, I can't run gotop for more than 24 hours because -- whether due to a sleep/resume or some other random condition -- gotop inevitably receives a value it doesn't like, raises an Error, and panics out.  On Linux, this appears to happen most with the net widget; maybe when my wireless goes down temporarily?  I can't tell.  But I'm baffled why you wrote the application to panic when gotop can't interpret a value.

**Comment by cjbassi** [comment]
I can go ahead and work around some of the issues that cause gotop to crash. I initially created the `Error` function to handle certain panics users were having in order to cleanly close the termbox library and prevent the terminal from being unusable so users could actually see/report the stack trace. I would still like invalid values to be reported though, so I guess I could create a log file when something bad happens but I'm open to other suggestions too.

Also, feel free to create a new issue or add info to any current ones when you have a panic. I saw you reported the integer divided by 0 panic but I do need a stack trace before I can work with that.

**Comment by cjbassi** [comment]
Yah unfortunately there's no way to handle panics globally in Go so you have to attack each panic when it comes up with the custom made `Error` function. Either that or run gotop with stderr redirected to a file.

**Comment by serussell** [comment]
Thanks for the fixes!

**Comment by cjbassi** [comment]
Can you check the log file at `~/.config/gotop/log`? I'm not intentionally panicking in gotop anymore, just logging all explicit errors now.

**Comment by cjbassi** [comment]
This looks like an internal error in gopsutil when fetching cpu usage, and in the go standard library when running `ps` with the `exec` command. I wonder if it's because you built it on a different machine than you ran it on. Not really sure.

**Comment by serussell** [comment]
Hm.  I'll have to wait for it to crash again, I think.

Related, this might be a problem:

```
util% ls -hl !$
-rw-r----- 1 ser ser 67M Dec  7 12:25 .config/gotop/errors.log
```

That's 67MB in fewer than 24 hours.  It's just this message repeated 2 to 4 times a second:

```
11:23:29 proc_unix.go:41: failed to convert third field to float: strconv.ParseFloat: parsing "client": invalid syntax. split: [26104 tmux: client 0.0 0.0 tmux attach]
```

On a second machine, it's the same message resulting in 35MB in 24 hours. On another, same message but only 56K.  On a third, no errors at all in the log. On my laptop, where I built the binary and have been running for a couple of days, it's 190MB, predominantly the float parse message at `proc_unix.go:41` except for two errors from `net.go:63` and `net.go:68`.

**Comment by cjbassi** [comment]
Wow that's a lot of logs. What's happening is that we run `ps` every second and gather its output, then split the commands by line, then split the columns on whitespace, then parse the columns into the appropriate data type. But `tmux: client` breaks that logic by taking up 2 columns. Glad we caught that though. I'll think about how we can fix that.

**Comment by cjbassi** [comment]
So I switched from parsing `ps` on whitespace, to settings the columns to a fixed width and substringing the row based on that width. And its working for me now when using tmux. Let me know if it works for you and if you get any other errors.

**Comment by serussell** [comment]
Hi @cjbassi 

Thanks again for all the hard work and attention to this.

This is much more stable; it's been running for the past couple of days and has crashed on only one machine:

```
created by github.com/cjbassi/gotop/src/widgets.NewProc
        /home/ser/src/github.com/cjbassi/gotop/src/widgets/proc.go:65 +0x189

goroutine 10 [chan receive]:
github.com/cjbassi/gotop/src/widgets.NewMem.func1(0xc00001a500)
        /home/ser/src/github.com/cjbassi/gotop/src/widgets/mem.go:32 +0x8a
created by github.com/cjbassi/gotop/src/widgets.NewMem
        /home/ser/src/github.com/cjbassi/gotop/src/widgets/mem.go:30 +0x2a6

goroutine 391216 [sleep]:
time.Sleep(0x3b9aca00)
        /usr/lib/go/src/runtime/time.go:105 +0x14f
github.com/shirou/gopsutil/cpu.PercentWithContext(0x5bccc0, 0xc0000120e8, 0x3b9aca00, 
01, 0x451de0, 0xc000131ec8, 0x4a65bb, 0xc00025a4a8, 0x0)
        /home/ser/src/github.com/shirou/gopsutil/cpu/cpu.go:158 +0x84
github.com/shirou/gopsutil/cpu.Percent(0x3b9aca00, 0xc000131f01, 0x10, 0x565500, 0xc00
0, 0xc000131f58, 0x405cbe)
        /home/ser/src/github.com/shirou/gopsutil/cpu/cpu.go:144 +0x4c
github.com/cjbassi/gotop/src/widgets.(*CPU).update.func2(0xc0000b50e0)
        /home/ser/src/github.com/cjbassi/gotop/src/widgets/cpu.go:87 +0x4c
created by github.com/cjbassi/gotop/src/widgets.(*CPU).update
        /home/ser/src/github.com/cjbassi/gotop/src/widgets/cpu.go:86 +0x5d
```

The logs are manageable now, too:

Server      | Size
------      | ----
util | 0
app | 65kB
loir | 0
slyd | 0
sting | 0

**app**: I think I forgot to zero out the log file; it was last updated yesterday in the early AM, so I believe this is user error.

_However_: The one that crashed (`util`) generated no messages in the log file for the crash.  So... did I somehow disable logging?

**Comment by serussell** [comment]
Much more stable, but they've crashed again.  Curiously, the log files don't contain anything any more; and sorry for the limited backtrace -- this is all that's in the tmux history.

**util**
```bash
github.com/cjbassi/gotop/src/widgets.NewProc.func1(0xc0000d1140)                            
        /home/ser/src/github.com/cjbassi/gotop/src/widgets/proc.go:67 +0x8a
created by github.com/cjbassi/gotop/src/widgets.NewProc
        /home/ser/src/github.com/cjbassi/gotop/src/widgets/proc.go:65 +0x189

goroutine 547396 [sleep]:
time.Sleep(0x3b9aca00)
        /usr/lib/go/src/runtime/time.go:105 +0x14f
github.com/shirou/gopsutil/cpu.PercentWithContext(0x5bccc0, 0xc0000120e8, 0x3b9aca00, 0xc00$080701, 0x5bc0c0, 0xc0000ce490, 0x7f16ca882020, 0xc000080770, 0x1)
        /home/ser/src/github.com/shirou/gopsutil/cpu/cpu.go:158 +0x84
github.com/shirou/gopsutil/cpu.Percent(0x3b9aca00, 0xc000031f01, 0x10, 0xc000031ef8, 0xc000$31f30, 0x45f93a, 0x5bbe80)
        /home/ser/src/github.com/shirou/gopsutil/cpu/cpu.go:144 +0x4c
github.com/cjbassi/gotop/src/widgets.(*CPU).update.func2(0xc0000b50e0)
        /home/ser/src/github.com/cjbassi/gotop/src/widgets/cpu.go:87 +0x4c
created by github.com/cjbassi/gotop/src/widgets.(*CPU).update
        /home/ser/src/github.com/cjbassi/gotop/src/widgets/cpu.go:86 +0x5d
util% ls -lh .config/gotop/errors.log
-rw-r----- 1 ser ser 0 Dec  8 04:24 .config/gotop/errors.log
```

**loir**
```
02ee01, 0x405fc5, 0x42beec, 0xc00002ee90, 0x4533e0, 0xc000069e00)                     [0/32]
        /home/ser/src/github.com/shirou/gopsutil/cpu/cpu.go:158 +0x84
github.com/shirou/gopsutil/cpu.Percent(0x3b9aca00, 0xc000069e01, 0x4, 0xc00002efb0, 0xc00006
9e00, 0xc00002ef58, 0x405d1f)
        /home/ser/src/github.com/shirou/gopsutil/cpu/cpu.go:144 +0x4c
github.com/cjbassi/gotop/src/widgets.(*CPU).update.func2(0xc000077470)
        /home/ser/src/github.com/cjbassi/gotop/src/widgets/cpu.go:87 +0x4c
created by github.com/cjbassi/gotop/src/widgets.(*CPU).update
        /home/ser/src/github.com/cjbassi/gotop/src/widgets/cpu.go:86 +0x5d

goroutine 1249436 [sleep]:
time.Sleep(0x3b9aca00)
        /usr/lib/go/src/runtime/time.go:105 +0x14f
github.com/shirou/gopsutil/cpu.PercentWithContext(0x5bccc0, 0xc00008a058, 0x3b9aca00, 0x5044
01, 0x0, 0x0, 0x5c, 0x19, 0xc000000020)
        /home/ser/src/github.com/shirou/gopsutil/cpu/cpu.go:158 +0x84
github.com/shirou/gopsutil/cpu.Percent(0x3b9aca00, 0xc000069e01, 0x4, 0xc00002eef8, 0x428dc2
, 0xc000000008, 0xc0007620c0)
        /home/ser/src/github.com/shirou/gopsutil/cpu/cpu.go:144 +0x4c
github.com/cjbassi/gotop/src/widgets.(*CPU).update.func2(0xc000077470)
        /home/ser/src/github.com/cjbassi/gotop/src/widgets/cpu.go:87 +0x4c
created by github.com/cjbassi/gotop/src/widgets.(*CPU).update
        /home/ser/src/github.com/cjbassi/gotop/src/widgets/cpu.go:86 +0x5d
loir% ls -lh ~/.config/gotop/
total 0
-rw-r----- 1 ser ser 0 Dec  8 04:28 errors.log
```

**app**: still running

**slyd**: still running

**laptop**: still running, after multiple sleep/resume cycles, screen resizes (dock/undock), and compositor enable/disable.  Rock solid.  However, there is *no* `errors.log` file, so it's not being created.

I just pulled MASTER and will restart everywhere.

**Comment by cjbassi** [comment]
That's strange that stderr isn't being redirected to the log files and the log file isn't being created on your laptop. I'm not really sure what could be causing those issues. I think the best strategy is if you could play around with the source code and test it on your different machines. The main things are the `setupLogging` function which should create the logfile, and the `logging.StderrToLogFile` function which should enable stderr to logfile redirection using the dup2 syscall. You could add `panics` to the source code to try and get it to work, and maybe try running with/without tmux too. Just some ideas.

Also, I changed the log files so they're truncated when gotop starts to prevent them from getting too big. But if there's a better way to manage their size then let me know.

**Comment by serussell** [comment]
Log files are working great, thanks! Closing.
