### ISSUE TITLE
Support dynamic color schemes

### ISSUE THREAD

**Issue by Anachron** [cjbassi/gotop#55]
- The output of `uname -a`: Linux void-lap 4.17.14_2 #1 SMP PREEMPT Wed Aug 15 13:45:55 UTC 2018 x86_64 GNU/Linux
- Any relevenat hardware info: 
- Terminal shell (like zsh or bash): bash
- Terminal emulator (like iTerm or gnome terminal): st
- tmux version if using tmux: none

It would be cool if the colorscheme file was just a config file so we don't need to recompile gotop in order to create our own themes.

**Comment by cjbassi** [comment]
Hmm that's a good idea. Maybe have a config file at ~/.config/gotop/config or something. But also keep the built in colorschemes and still enable them with the flag option I think.

**Comment by cjbassi** [comment]
Instructions documented in the updated readme [here](https://github.com/cjbassi/gotop#colorschemes).

**Comment by Anachron** [comment]
Thanks so much!
