### ISSUE TITLE
tmux rendering issues

### ISSUE THREAD

**Issue by lz100** [cjbassi/gotop#59]
Please give the following info:

- The output of `uname -a`: Linux owl 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Any relevenat hardware info: Intel(R) Xeon(R) CPU           E7330  @ 2.40GHz
- Terminal shell (like zsh or bash): bash
- Terminal emulator (like iTerm or gnome terminal): gnome
- tmux version if using tmux: tmux/2.2

I'm trying to use gotop on a cluster computing centos 7 system, but the program can only detect a few CPUs. The right configuration shows like this htop image, 16 cores. The display in tmux is not right but outside tmux is fine.

- Inside tmux
![screenshot from 2018-09-12 05-07-23](https://user-images.githubusercontent.com/35240440/45448256-b0a0c800-b686-11e8-8790-e829acc72d1b.png)

- outside
![screenshot from 2018-09-12 05-27-36](https://user-images.githubusercontent.com/35240440/45448488-4fc5bf80-b687-11e8-9416-db685e6820eb.png)

- Right config
![screenshot from 2018-09-12 05-08-10](https://user-images.githubusercontent.com/35240440/45448260-b4344f00-b686-11e8-8ebe-8b3f98510db8.png)

**Comment by lz100** [comment]
Thanks for the info. I used gotop -p to display all cores. This doesn't fix the tmux display.

**Comment by edenist** [comment]
Confirming I've got the same issue with tmux, in both bash and zsh. 

FreeBSD trident 11.2-RELEASE-p4 FreeBSD 11.2-RELEASE-p4 #5 r340144: Mon Nov  5 11:27:55 AEDT 2018     root@trident:/usr/obj/usr/src/sys/TRIDENT  amd64

**Comment by wallace11** [comment]
> @wallace11 Did you get this issue on a previous version of tmux tho? I wasn't able to reproduce this with alacritty or gnome-terminal on any version of tmux back to 1.0.

Sorry, I wasn't trying to replicate this on another version...

**Comment by json-m** [comment]
> By the way, this bug doesn't appear on latest tmux version (2.8).

I do see this occurring on tmux 2.8, at least in Alpine Linux.

```
root at summit in ~
# tmux -V
tmux 2.8
```

**Comment by rephorm** [comment]
Is this a unicode display issue? https://askubuntu.com/questions/410048/utf-8-character-not-showing-properly-in-tmux suggests running "tmux -u" to fix a similar issue.

**Comment by cdiener** [comment]
Can confirm that running with `tmux -u` fixed the issue for me.

**Comment by lz100** [comment]
Confirm `tmux -u` fixed the issue.
