### ISSUE TITLE
Network rate values are doubled with vpn

### ISSUE THREAD

**Issue by MoEmanon** [cjbassi/gotop#61]
- The output of `uname -a`:
Linux MoeManjaro 4.19.0-1-MANJARO #1 SMP PREEMPT Thu Sep 20 19:27:32 UTC 2018 x86_64 GNU/Linux

- Any relevenat hardware info:
None

- Terminal shell (like zsh or bash):
zch

- Terminal emulator (like iTerm or gnome terminal):
urxvt

- tmux version if using tmux:
Nop

In network usage , my Tx/s and Rx/s values are doubled, i'm using a vpn and wifi tun0 and wlp3s0.

![2018-09-28-180654_1920x1080_scrot](https://user-images.githubusercontent.com/42699498/46220142-9125c280-c349-11e8-820c-fa7e9ebad534.png)

**Comment by cjbassi** [comment]
I think this is because gotop sums up the network activity across all the network interfaces. It looks like the usage stats of wlp3s0 + tun0 equals what's outputed by gotop. So we probably just need to hardcode some rules about ignoring vpn interfaces like tun0 from the network stats.
