### ISSUE TITLE
gotop -p CPU order with more than 10 CPUs

### ISSUE THREAD

**Issue by qqldd** [cjbassi/gotop#69]
Please give the following info:

- Terminal shell (like zsh or bash):
zsh
- Terminal emulator (like iTerm or gnome terminal):
Tilix

The CPU number seems sort with string not int. The output for 12 CPU is:

CPU0
CPU1
CPU10
CPU11
CPU2
...

![foo123](https://user-images.githubusercontent.com/233128/47679743-366acb00-db82-11e8-836b-ac595191d1ec.png)

**Comment by aminalaee** [comment]
@cjbassi I was thinking implementing natural sorting in termui or using a library would solve the issue. Is it ok? Do you have any suggestions?

**Comment by cjbassi** [comment]
We actually just got a PR to fix this, but thanks for asking! Should be merged soon but just figuring out some formatting.

**Comment by cjbassi** [comment]
Should be fixed now with 1b8c3ed91889363e6eb60f793b4fd01b7ec7805d.
