### ISSUE TITLE
Addition of a Clock Widget?

### ISSUE THREAD

**Issue by TheCedarPrince** [cjbassi/gotop#72]
I really like GoTop - I usually have it full screen on one of my monitors. 

Would there be any way there could be a built-in clock widget to display time as my task bar is taken up by the GoTop terminal I have in maximum size? 

Thanks!

**Comment by cjbassi** [comment]
Would you prefer to have the time in a statusbar like in [vtop](https://github.com/MrRio/vtop) or add a new widget that works like the [tmux clock](http://cdated.com/wp-content/uploads/2012/11/tmux1.png)?

**Comment by TheCedarPrince** [comment]
I was envisioning something more like vtop except the widget could be placed in a small box above (or below - whichever looks nicer) the disk usage and temperatures widget. 

![image](https://user-images.githubusercontent.com/29561456/49253139-eaff4300-f3f3-11e8-99eb-f14e606be6ea.png)

What we could play around with is looking at the vertical gap at the bottom of gotop (as you can see in my picture) which spans the entirety of the command prompt.

I'd be happy to test things out but I do not have the skill nor bandwidth to make the widget right now...

Thanks @cjbassi!

**Comment by cjbassi** [comment]
So the gap at the bottom is actually just a rounding error. It goes away on certain terminal sizes. But we could also just create a space at the bottom for a clock/statusbar.

**Comment by TheCedarPrince** [comment]
Great! Let's try it at @cjbassi !

**Comment by cjbassi** [comment]
So you can now add a statusbar with a clock by passing the `-b` flag. :smile:  Let me know if it works for you or if we should change anything with it.

**Comment by cjbassi** [comment]
Just added a clock widget, so I decided to change the statusbar so its now enabled with `-s`. Breaking change ik, but we just added this so no biggie I assume. :D

**Comment by cjbassi** [comment]
You can do `go get -u github.com/cjbassi/gotop` to install it into your gopath. The `-u` flag allows the package to be updated if it's already installed. Or you can install `gotop-git` from the AUR if you're on Arch Linux. Or to build an executable that you can do what you want with, you can do
```
git clone https://github.com/cjbassi/gotop && cd gotop && go build
```
Hope that helps :)

**Comment by TheCedarPrince** [comment]
Hey @cjbassi - tried to use go to update via my gopath and ran into this error: 

`go get -u github.com/cjbassi/gotop
package context: unrecognized import path "context" (import path does not begin with hostname)`

My go version is go1.6.2 linux/amd64.

Any idea about why this is happening? 

CP

**Comment by cjbassi** [comment]
So the issue there is that the `context` package was added in Go 1.7, so you'd have to update Go. Not sure which package is using it. I'm planning on releasing a new version of gotop soon if that helps too.
