### ISSUE TITLE
Arch Linux `gotop-bin` to `gotop`

### ISSUE THREAD

**Issue by erayaydin** [cjbassi/gotop#74]
Currently, in `README.md` file, we suggest `gotop-bin` package to install for Arch Linux. But, installing `gotop` is better for multi architecture. I think we should replace `gotop-bin` install suggest to `gotop`

**Comment by cjbassi** [comment]
Thanks for the recommendation. I went ahead and referenced all 3 packages that are available to install gotop from in the readme so users can install whichever they prefer.

**Comment by erayaydin** [comment]
Thank you for this lovely project :heart:
