### ISSUE TITLE
Crash when switching VPN on and off.

### ISSUE THREAD

**Issue by Sojiro84** [cjbassi/gotop#78]
So, I just had gotop crash on me for the first time. I had my normal internet first, then many hours later I turned my VPN on and 5 minutes later off again and then it crashed with a error log. I assume you would like to know about it!

> Error caught. Exiting program.
> 
> Issue with net data.
> 
> Diagnostics:
> curRecvTotal: 36264064936
> curSentTotal: 3171588059
> self.prevRecvTotal: 36451123116
> self.prevSentTotal: 3180327480
> recvRecent: 18446744073522493436
> sentRecent: 18446744073700812195
> int(recvRecent): -187058180
> int(sentRecent): -8739421
> 
> panic: 1
> 
> goroutine 50 [running]:
> github.com/cjbassi/gotop/src/utils.Error(0x59370b, 0x8, 0xc000208000, 0xe9)
> 	/home/cjbassi/playground/gotop/src/utils/utils.go:67 +0x23f
> github.com/cjbassi/gotop/src/widgets.(*Net).update(0xc0001b2020)
> 	/home/cjbassi/playground/gotop/src/widgets/net.go:62 +0x4f7
> github.com/cjbassi/gotop/src/widgets.NewNet.func1(0xc0001b2020)
> 	/home/cjbassi/playground/gotop/src/widgets/net.go:39 +0x72
> created by github.com/cjbassi/gotop/src/widgets.NewNet
> 	/home/cjbassi/playground/gotop/src/widgets/net.go:36 +0x273

**Comment by cjbassi** [comment]
This was just closed with c7171781c13f2bdd2f3cffd149800426a97dd4c2, but thanks for relaying the info!
