### ISSUE TITLE
Raspberry compatibility

### ISSUE THREAD

**Issue by azlux** [cjbassi/gotop#8]
Hi,
Can you compile Gotop for the raspberry architecture (ARM) to having it into the release page ?
```
uname -a
Linux minibian 4.9.80-v7+ #1098 SMP Fri Mar 9 19:11:42 GMT 2018 armv7l GNU/Linux
```
With `env GOOS=linux GOARCH=arm GOARM=5 go build`
Thank

**Comment by cjbassi** [comment]
For sure, but wouldn't it be `GOARM=7` since uname gives `armv7l`?

**Comment by Kealper** [comment]
Depends on the Raspberry Pi in use, you may wish to use `GOARM=6` instead, as the older Pis and the low-cost Pi Zeros use ARMv6 cores, although newer ones are ARMv7 and ARMv8.

**Comment by cjbassi** [comment]
Just released binaries for all arm versions which you can automatically download with the download.sh script. It picks the right one for your system. Let me know if there's any issues!
