### ISSUE TITLE
github.com/shirou/gopsutil/cpu doesn't exist

### ISSUE THREAD

**Issue by yurivict** [cjbassi/gotop#82]
You refer here to ```github.com/shirou/gopsutil/cpu``` but it doesn't exist: https://github.com/cjbassi/gotop/blob/master/src/widgets/cpu.go#L9

**Comment by cjbassi** [comment]
What do you mean 'doesn't exist'? It's a valid import path although not a valid url.

**Comment by yurivict** [comment]
It can't find it. Aren't all github.com/* packages supposed to come from github URLs?


```
===>  Building for gotop-1.7.0
src/widgets/cpu.go:9:2: cannot find package "github.com/shirou/gopsutil/cpu" in any of:
	/usr/local/go/src/github.com/shirou/gopsutil/cpu (from $GOROOT)
	/usr/ports/sysutils/gotop/work/gotop-1.7.0_GH0/src/github.com/shirou/gopsutil/cpu (from $GOPATH)
src/widgets/disk.go:12:2: cannot find package "github.com/shirou/gopsutil/disk" in any of:
	/usr/local/go/src/github.com/shirou/gopsutil/disk (from $GOROOT)
	/usr/ports/sysutils/gotop/work/gotop-1.7.0_GH0/src/github.com/shirou/gopsutil/disk (from $GOPATH)
src/widgets/mem.go:10:2: cannot find package "github.com/shirou/gopsutil/mem" in any of:
	/usr/local/go/src/github.com/shirou/gopsutil/mem (from $GOROOT)
	/usr/ports/sysutils/gotop/work/gotop-1.7.0_GH0/src/github.com/shirou/gopsutil/mem (from $GOPATH)
src/widgets/net.go:10:2: cannot find package "github.com/shirou/gopsutil/net" in any of:
	/usr/local/go/src/github.com/shirou/gopsutil/net (from $GOROOT)
	/usr/ports/sysutils/gotop/work/gotop-1.7.0_GH0/src/github.com/shirou/gopsutil/net (from $GOPATH)
*** Error code 1
```

**Comment by cjbassi** [comment]
Oh, hmm. Have you tried to do `go get .`? Also, are you using go 1.11?

**Comment by yurivict** [comment]
> Have you tried to do go get .?

I am trying to create the FreeBSD port. It isn't allowed to download dependencies. They need to be pre-downloaded.

I use ```go-1.11```.

**Comment by cjbassi** [comment]
What do you mean you're not allowed to download dependencies? You can't `go get`? The only other solution is to vendor, right? But I removed vendoring from this project.

**Comment by yurivict** [comment]
I download them and place into the directory hierarchy.
Random external projects can't be downloaded without being fingerprinted for security reasons.

**Comment by cjbassi** [comment]
Oh I see, I didn't realize you were making a FreeBSD package. Well I'm not sure how it works with FreeBSD. I know with Arch you can just clone the repo and run `go build`. I'm not sure of another way of downloading go dependencies. You wouldn't really do that manually. You would use the `go` cli tool to get the proper versions etc. The only other solutions is vendoring I think but I actually just stopped vendored dependencies because it was annoying.

**Comment by yurivict** [comment]
Where does ```github.com/shirou/gopsutil/cpu``` come from?

**Comment by yurivict** [comment]
Just cloning and running ```go build``` is insecure, because there is no guarantee that it will download the same files every time. Nobody knows where they are coming from, and they aren't fingerprinted.

**Comment by cjbassi** [comment]
`github.com/shirou/gopsutil/cpu` comes from `https://github.com/shirou/gopsutil/tree/master/cpu`.

Yah I see where you're coming from, programming language package managers do have issues with security. But Go modules does include `Gopkg.lock` which is deterministic and downloads a specific commit from GitHub which is kindof like a fingerprint, so while you may not be able to specify the fingerprints directly from the FreeBSD package, it is specified from within the go package. Does FreeBSD give you the option of running `go build`? Or does it block you from running that or something?

**Comment by yurivict** [comment]
> a specific commit from GitHub which is kindof like a fingerprint

Commit hashes aren't like fingerprints. There is nothing in the Git protocol that guarantees that the returned file actually corresponds to the commit. In fact, compromised Git servers can return any files at all.

**Comment by yurivict** [comment]
Thank you for resolving this issue. ```https://github.com/shirou/gopsutil/tree/master/cpu``` works.
