### ISSUE TITLE
Build fails: type *Temp has no field or method update

### ISSUE THREAD

**Issue by yurivict** [cjbassi/gotop#83]
```
===>  Building for gotop-1.7.0
# github.com/cjbassi/gotop/src/widgets
src/widgets/temp.go:38:6: self.update undefined (type *Temp has no field or method update)
src/widgets/temp.go:43:8: self.update undefined (type *Temp has no field or method update)
*** Error code 2
```

gotop-1.7.0
termui rev. e8dd23f

**Comment by cjbassi** [comment]
Just pushed a commit to master to make sure the right files are built on freebsd, although I'm not sure if the functionality of the code will work on freebsd yet. Can you test master and let me know what happens?

**Comment by yurivict** [comment]
It works, cool!

Thank you for fixing all issues. I will create the port shortly.
