### ISSUE TITLE
Panic on Mac caused by cpu percentages issue

### ISSUE THREAD

**Issue by ehlxr** [cjbassi/gotop#9]
```
panic: runtime error: index out of range

goroutine 6 [running]:
github.com/cjbassi/gotop/widgets.(*CPU).update(0xc42000afc0)
	/home/cjbassi/go/src/github.com/cjbassi/gotop/widgets/cpu.go:52 +0x3c9
created by github.com/cjbassi/gotop/widgets.NewCPU
	/home/cjbassi/go/src/github.com/cjbassi/gotop/widgets/cpu.go:35 +0x2cc
```

**Comment by chlins** [comment]
![2018-04-09 4 54 09](https://user-images.githubusercontent.com/31262637/38488644-ac7dcc72-3c16-11e8-9e91-9806bdb83160.png)
Mac OS 10.13.3

**Comment by heruan** [comment]
Same here, running macOS 10.13.4

**Comment by danielmunoz** [comment]
Same. Running `macOS 10.12.6`.

```
panic: runtime error: index out of range

goroutine 6 [running]:
github.com/cjbassi/gotop/widgets.(*CPU).update(0xc42000b080)
	/home/cjbassi/go/src/github.com/cjbassi/gotop/widgets/cpu.go:52 +0x3c9
created by github.com/cjbassi/gotop/widgets.NewCPU
	/home/cjbassi/go/src/github.com/cjbassi/gotop/widgets/cpu.go:35 +0x2cc
```

**Comment by cjbassi** [comment]
I don't have a mac to test on, but I just pushed a commit to the repo and I'd appreciate if someone could `go get github.com/cjbassi/gotop`, run gotop, and then let me know what happens or what the error messages are this time. Thanks!

**Comment by cjbassi** [comment]
@chlins is a different issue I think, same as #12.

**Comment by cjbassi** [comment]
@petermbenjamin Are you also on OSX? What terminal are you using?

**Comment by cjbassi** [comment]
Also, when are the issues happening?

**Comment by petermbenjamin** [comment]
@cjbassi - ok, some updates.

- I tried it on `Terminal.app` (native terminal client on macOS). It took a few minutes (~ 1-2 mins) before `gotop` displayed the visualizations.
<img width="762" alt="screen shot 2018-04-09 at 1 28 40 pm" src="https://user-images.githubusercontent.com/6811830/38521287-17d01ae2-3bfa-11e8-94a8-76f47ef6d90b.png">

- I tried it on `iTerm` and waited a few minutes to compare. It erred out with the following error message:
<img width="922" alt="screen shot 2018-04-09 at 1 31 30 pm" src="https://user-images.githubusercontent.com/6811830/38521392-5b9caf74-3bfa-11e8-919d-8e9825ca5a15.png">

**Comment by cjbassi** [comment]
@petermbenjamin I appreciate all the troubleshooting you're doing. Looks like the index out of range error is the same one that chlins is getting. I just pushed some changes that include better error logging so it'd help if you could update and build/run from source and see what the errors give you this time.

**Comment by cjbassi** [comment]
@viktor-evdokimov I think the issue there is that the default colorscheme for gotop has a transparent background which doesn't look great on white colored terminals. You could try one of the other colorschemes by using the `-c` flag, or if none of those work I could add a colorscheme that better suits white backgrounds.

**Comment by cjbassi** [comment]
@viktor-evdokimov Just added the 'default-dark' colorscheme for brighter backgrounds to the latest release. Let me know if that works or if there's till issues.

**Comment by petermbenjamin** [comment]
@cjbassi - Indeed. 
Tested by running:
```
$ go get -u -v github.com/cjbassi/gotop
$ gotop
```

But, it's still taking about a minute before anything appears on the screen. I am not sure why. 

Would you like me to open a separate GH issue for the slow startup time on macOS?
Also, any pointers/directions on troubleshooting/debugging this problem?

**Comment by cjbassi** [comment]
@petermbenjamin Yah I think opening a new issue would be good.

I think the best way to debug the slow startup is to throw a bunch of fmt.Println("1"), fmt.Println("2"), etc into main.go and see where the program hangs for a while. If you're not familiar with Go I could create a branch with the print statements for you to test, just let me know.

**Comment by petermbenjamin** [comment]
I will create a new issue and try to fmt.Println debug it and will let you
know what I find.

**Comment by heliostatic** [comment]
Also on 10.12.6, clean install via 
```
$ go get -u -v github.com/cjbassi/gotop
$ gotop
```
and this is the error I'm getting after about 45-60 seconds:

```
Error caught. Exiting program.

Issue with CPU percentages.

Diagnostics:
self.Count: 4
gopsutil.Counts(): 4
len(percents): 0
percents: []
self.interval: 1s

panic: 1

goroutine 19 [running]:
github.com/cjbassi/gotop/utils.Error(0x1183b16, 0xf, 0xc42017e060, 0x52)
	/home/cjbassi/go/src/github.com/cjbassi/gotop/utils/utils.go:30 +0x23f
github.com/cjbassi/gotop/widgets.(*CPU).update(0xc420092fa0)
	/home/cjbassi/go/src/github.com/cjbassi/gotop/widgets/cpu.go:55 +0x532
created by github.com/cjbassi/gotop/widgets.NewCPU
	/home/cjbassi/go/src/github.com/cjbassi/gotop/widgets/cpu.go:37 +0x2d3
```

**Comment by cjbassi** [comment]
@heliostatic So the program runs and works for about 45 seconds and then gives that error?

**Comment by heliostatic** [comment]
@cjbassi Good clarification--No, it sits at a blank terminal and then errors out.

**Comment by rkumar** [comment]
Getting this on OSX Sierra on both iTerm and Terminal. Nothing happens for half a minute, then I get this error. Installed using homebrew.

> Error caught. Exiting program.
> 
> Issue with CPU percentages.
> 
> Diagnostics:
> self.Count: 8
> gopsutil.Counts(): 8
> len(percents): 0
> percents: []
> self.interval: 1s
> 
> panic: 1
> 
> goroutine 17 [running]:
> github.com/cjbassi/gotop/utils.Error(0x1184197, 0xf, 0xc4201ba060, 0x52)
> 	/home/cjbassi/go/src/github.com/cjbassi/gotop/utils/utils.go:30 +0x23f
> github.com/cjbassi/gotop/widgets.(*CPU).update(0xc420156000)
> 	/home/cjbassi/go/src/github.com/cjbassi/gotop/widgets/cpu.go:57 +0x532
> created by github.com/cjbassi/gotop/widgets.NewCPU
> 	/home/cjbassi/go/src/github.com/cjbassi/gotop/widgets/cpu.go:38 +0x2d3

**Comment by stephencornelius** [comment]
I get the same issue as @rkumar when installing via brew but it works when installing via goget

**Comment by maxtar** [comment]
Have the same issue in Windows:
`Error caught. Exiting program.

Issue with CPU percentages.

Diagnostics:
self.Count: 8
gopsutil.Counts(): 8
len(percents): 0
percents: []
self.interval: 1s

panic: 1

goroutine 17 [running]:
github.com/cjbassi/gotop/utils.Error(0x5a120a, 0xf, 0xc0421720c0, 0x52)
        d:/WLCR/GoProjects/src/github.com/cjbassi/gotop/utils/utils.go:30 +0x246
github.com/cjbassi/gotop/widgets.(*CPU).update(0xc042140000)
        d:/WLCR/GoProjects/src/github.com/cjbassi/gotop/widgets/cpu.go:57 +0x539
created by github.com/cjbassi/gotop/widgets.NewCPU
        d:/WLCR/GoProjects/src/github.com/cjbassi/gotop/widgets/cpu.go:38 +0x2da`

Did by 
```
$ go get -u -v github.com/cjbassi/gotop
$ gotop
```

**Comment by f1337** [comment]
Worked for me, just now, with a 20-second startup delay (timed with stopwatch). I compiled from source:

```
go get -u -v github.com/cjbassi/gotop
gotop
```

My system details:
macOS High Sierra 10.13.4
MacBook Pro (Retina, 15-inch, Mid 2015)
Processor: 2.5 GHz i7
Memory: 16 GB

**Comment by cjbassi** [comment]
Thanks for all the info and sorry people have been having issues. It turns out gopsutil has some issues on OSX which makes gotop unusable on OSX right now. Hoping to fix that in the future, but I also don't have a mac to test on right now so idk how long it will take. Going to close this issue and open another one that pools the issues people have been having on OSX.

**Comment by maxtar** [comment]
What about windows?

**Comment by cjbassi** [comment]
@maxtar gotop is untested on windows but feel free to try it and let me know if it works or create an issue if it doesn't. I'd be happy to add support if people want it.

**Comment by maxtar** [comment]
@cjbassi As I mentioned [here](https://github.com/cjbassi/gotop/issues/9#issuecomment-381520145) I've got the same issue. Need I creating new issue fro windows?

**Comment by cjbassi** [comment]
@maxtar Oh sorry, I didn't see that you were having the same issue on windows. But yah actually if you create a new issue for that, that would be great. Thanks.

**Comment by cjbassi** [comment]
gotop should be working on OSX now, and you can install using either Git, Homebrew, or from Source as documented in the readme. Let me know if you're still having any issues! Thanks @f1337 for helping get it to work!
