### ISSUE TITLE
Overlay issue while in help mode

### ISSUE THREAD

**Issue by wallace11** [cjbassi/gotop#90]
- gotop version (`gotop -v`): 1.7.1
- The output of `uname -a`: Linux odroid 4.14.87-1-ARCH #1 SMP PREEMPT Wed Dec 12 01:03:45 UTC 2018 armv7l GNU/Linux
- Terminal shell (like zsh or bash): zsh
- Terminal emulator (like iTerm or gnome terminal): Irrelevant
- Any relevenat hardware info: None
- tmux version if using tmux: 2.8

Also please copy or attach the following file if it exists and contains logs:

- Linux: `~/.config/gotop/errors.log`
- OSX: `~/Library/Application Support/gotop/errors.log`

==========

This is a funny one and should be easy to fix (I think).

Steps to reproduce:
1. Go into help (`?`) mode.
2. Press up/down/j/k.
3. Process tab is overlayed on top of  help page.

Nothing harmful there ;)

Cheers.

**Comment by cjbassi** [comment]
:laughing: Yah that's a good one. I've run into it before and I thought I fixed it but somehow it crept up again. Thanks!
