### ISSUE TITLE
Update the version?

### ISSUE THREAD

**Issue by serussell** [cjbassi/gotop#91]
There are two new widgets; that's cause for celebration, including updating the version string (which hasn't changed since mid-December).

**Comment by cjbassi** [comment]
A new version would be good, but I introduced some breaking changes and would have to do a major version bump, so I'm just holding out a little bit. And I just added some breaking changes yesterday too so there's that :D

**Comment by cjbassi** [comment]
Just released 2.0.0 :tada: Thanks for your additions btw!
