### ISSUE TITLE
The custom colorschemes simply doesn't work

### ISSUE THREAD

**Issue by hrqmonteiro** [cjbassi/gotop#93]
Required information:

- gotop version: 1.7.1
- The output of `uname -a`: Linux motherbase 4.20.1-arch1-1-ARCH #1 SMP PREEMPT Wed Jan 9 20:25:43 UTC 2019 x86_64 GNU/Linux
- Terminal shell (e.g. zsh or bash): Bash
- Terminal emulator (e.g. iTerm or gnome terminal): urxvt and Termine

The custom colorscheme doesnt work. I use the default.json as a base and save a file .json on .config/gotop and ok, if i run gotop -c name.json it opens gotop, but then it doesnt matter if i edit the values, ANYTHING i change on the numbers on fg, bars or anything it simply does no effect, it remains the same, the same colors as if i just type gotop on the terminal

**Comment by hrqmonteiro** [comment]
![2019-01-15-010614_1580x843_scrot](https://user-images.githubusercontent.com/17055027/51156253-dbcc3b80-1861-11e9-8782-bd88797cac69.png)
![2019-01-15-010630_1727x902_scrot](https://user-images.githubusercontent.com/17055027/51156254-dbcc3b80-1861-11e9-958a-b9dbcb52b86a.png)

It just doesn't work

**Comment by cjbassi** [comment]
Should be working now. Was just a simple logic error :expressionless:

**Comment by hrqmonteiro** [comment]
Still not working here. Just tried.

**Comment by hrqmonteiro** [comment]
I even searched on Unixporn and stuff to see if someone provided a .json file of a custom theme just for me to see if something went wrong with mine, but couldnt find it

But i pretty much just edited the file as is said on the tutorial and it doesnt matter how many i change the colors it just remains default

**Comment by cjbassi** [comment]
Did you update gotop? And has the filename been changed from `default.json` to something else?

**Comment by cjbassi** [comment]
Also, there's currently some issues installing gotop. I'm not sure what platform you're on but the most reliable way is to `git clone https://github.com/cjbassi/gotop && cd gotop && go install`, at least for the latest master version.

**Comment by cjbassi** [comment]
Hmm, I would try git cloning, then running `go run main.go -c ...` to make sure there isn't any issues with your path.

**Comment by hrqmonteiro** [comment]
This works, it runs gotop, but i'm unable to run it just by typing gotop, then

But thats ok

**Comment by cjbassi** [comment]
Glad it works! And installing should be working now. So either `go get -u github.com/cjbassi/gotop` or installing `gotop-git` from the AUR depending on how you originally installed it.
