### ISSUE TITLE
Recurring panics

### ISSUE THREAD

**Issue by serussell** [cjbassi/gotop#96]
# What's up

I'm running gotop in a tmux session on a cloud VM server. I connect to this session via mosh; it's always on.  This is one of four such servers, of which one is hosted by an entirely different company.  gotop was compiled on my laptop and then scp'd over to each of these machines.

Two of these gotop sessions regularly crash.  I've been unable to discern a pattern to when it happens; it happens on one server at least once every couple of days.  The other server, on the different hosting provider, seems to be a bit more stable (it's currently been running for about a week).  The other two gotop instances on the other machines do not crash.

I've attached three such crash logs.  Two appear to be complaining about concurrent writes to a map, which is verbotten as go maps are not thread safe; that's at the top of the second and third log files.

# Required information:

- gotop version (`gotop -v`): **1.7.1**
- The output of `uname -a`: **Linux util 2.6.32-042stab120.6 #1 SMP Thu Oct 27 16:59:03 MSK 2016 x86_64 GNU/Linux**
- Terminal shell (e.g. zsh or bash): **zsh 5.3.1 (x86_64-debian-linux-gnu)**
- Terminal emulator (e.g. iTerm or gnome terminal): **termite v14**
- Any relevenat hardware info: **Running in a VM in the cloud**
- tmux version if using tmux: **tmux 2.3**
- mosh version: **mosh 1.2.6**

Also please copy or attach the following file if it exists and contains logs:

[gotop.errors.log](https://github.com/cjbassi/gotop/files/2797938/gotop.errors.log)
[gotop.errors.2.log](https://github.com/cjbassi/gotop/files/2797942/gotop.errors.2.log)
[gotop.errors.3.log](https://github.com/cjbassi/gotop/files/2797943/gotop.errors.3.log)

**Comment by cjbassi** [comment]
And one other thing: the logfile path was changed to `~/.local/state/gotop/errors.log` as of a couple weeks ago.

**Comment by serussell** [comment]
I'm copying 2.0.0 to the machines and will report back early next week, which should be enough time for any to fail (if they are going to).

**Comment by serussell** [comment]
Closing as likely related to #99, which is confirmed fixed.

**Comment by serussell** [comment]
@cjbassi, wanted to follow up.  gotop is now stable.

Since my last update (2.0.1), it's been running on all of my machines without crash, and without issue.  At least for me, it looks like all of the stability issues have been resolved.

**Comment by cjbassi** [comment]
That's great to hear :smile: Feels like we came a long way in resolving all the issues. And I really appreciate all your help and reporting all the issues you were having.
