### ISSUE TITLE
Crash shortly after starting

### ISSUE THREAD

**Issue by serussell** [cjbassi/gotop#99]
# Summary

Freshly baked 2.0.0; gotop crashes shortly after running for a few minutes.  Per `time`, 2 minutes, 40 seconds after starting.

# Required information:

- gotop command: **gotop -b -s -c monokai -p -a**
- gotop version (`gotop -v`): **2.0.0**
- The output of `uname -a`: **Linux sting 4.20.0-arch1-1-ARCH #1 SMP PREEMPT Mon Dec 24 03:00:40 UTC 2018 x86_64 GNU/Linux**
- Terminal shell (e.g. zsh or bash): **zsh 5.6.2 (x86_64-pc-linux-gnu)**
- Terminal emulator (e.g. iTerm or gnome terminal): **termite v14**
- Any relevenat hardware info: **Dell XPS13 9343**
- tmux version if using tmux: **tmux 2.8**

[gotop.errors.log](https://github.com/cjbassi/gotop/files/2799224/gotop.errors.log) (from ~/.local/state/gotop).

**Comment by serussell** [comment]
## Update 1
Does not crash after a half-hour when run with no options.

**Comment by cjbassi** [comment]
So I think this is the same concurrent map write issue as #96, which turned out to be a different issue than I fixed before. This one is particular to the CPU widget, which potentially spawns 2 goroutines when updating, which each write to the same map. Should be fixed on master now. Thanks again, I should've checked the logs more carefully.

**Comment by serussell** [comment]
Think I noted this on another ticket, but I'll be able to check this after Feb 8.  Thanks for being patient on my confirmation!

**Comment by serussell** [comment]
I'm going to close this as confirmed fixed; I updated `gotop` on the VMs and they've all been running for over a half hour, so any other stability issues probably have some other root cause.

Thanks again for the fix!
